version: "2.2"

services:
  fastapi: 
    build: .
    container_name: fastapi_prueba
    ports: 
      - "8000:8000"
    depends_on:
      - prueba_postgres
    env_file:
      - .env

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
    volumes:
      - .:/app
  prueba_postgres:
    image: postgres:alpine
    container_name: postgres_prueba
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
      